"""LPF filter test module.

Notes:
    LPF filter is a filter of a line profile generated by LPF Direct method.
    This filter is used in MODIT/PreMODIT to convolve the line profile.
    Reading this tests, one may understand the relation between the open and closed lpffilter, and the analytical Voigt kernel in ditkernel.
    The dimension of the open filter is odd, and the dimension of the closed filter is even.

"""
import pytest
import jax.numpy as jnp
import numpy as np
from exojax.opacity._common.lpffilter import generate_closed_lpffilter
from exojax.opacity._common.lpffilter import generate_open_lpffilter


def test_generate_closed_lpffilter():
    filter_length_oneside, nsigmaD, ngammaL = _test_values_lpffilter()
    shapefilter = generate_closed_lpffilter(filter_length_oneside, nsigmaD, ngammaL)
    ref = _refvalue_closed_lpffilter()
    assert jnp.allclose(shapefilter, ref)


def test_generate_open_lpffilter():
    filter_length_oneside, nsigmaD, ngammaL = _test_values_lpffilter()
    shapefilter = generate_open_lpffilter(filter_length_oneside, nsigmaD, ngammaL)
    ref = _refvalue_open_lpffilter()
    assert jnp.allclose(shapefilter, ref)


def _refvalue_open_lpffilter():
    openref = jnp.array(
        [
            0.00937768,
            0.01388492,
            0.02281364,
            0.04338582,
            0.09071519,
            0.16579562,
            0.20870925,
            0.16579562,
            0.09071519,
            0.04338582,
            0.02281364,
            0.01388492,
            0.00937768
        ]
    )
    return openref


def _refvalue_closed_lpffilter():
    openref = _refvalue_open_lpffilter()
    openref = openref[:-1]
    filter_length_oneside, nsigmaD, ngammaL = _test_values_lpffilter()
    closeref = jnp.concatenate(
        [openref[filter_length_oneside:], openref[:filter_length_oneside]]
    )
    return closeref


def _test_values_lpffilter():
    filter_length_oneside = 6
    nsigmaD = 1.0
    ngammaL = 1.0
    return filter_length_oneside, nsigmaD, ngammaL





@pytest.mark.parametrize("i", [0, -1])
def test_lpffilter_aliasing_area(i):
    from exojax.signal.ola import _fft_length
    
    filter_length_oneside, nsigmaD, ngammaL = _test_values_lpffilter()

    # shape filter
    shapefilter = generate_open_lpffilter(filter_length_oneside, nsigmaD, ngammaL)
    filter_length = len(shapefilter)

    # signal setting
    signal_length = 14
    signal = np.zeros(signal_length)
    signal[i]= 1.0

    # OLA size setting
    fft_length = _fft_length(signal_length, filter_length)


    # OLA zero-padding
    filter_zeropad = np.zeros(fft_length)
    filter_zeropad[:filter_length] = shapefilter
    signal_zeropad = np.zeros(fft_length)
    signal_zeropad[:signal_length] = signal
    # convolution
    fft_filter = jnp.fft.rfft(jnp.array(filter_zeropad))
    fft_signal = jnp.fft.rfft(jnp.array(signal_zeropad))
    conv = jnp.fft.irfft(fft_filter * fft_signal)
    # no aliasing area
    edge = filter_length_oneside
    noaliase_area = conv[edge:-edge]
    
    if i==0:
        diff = noaliase_area[0:filter_length_oneside+1] - shapefilter[filter_length_oneside:]
    elif i==-1:
        diff = noaliase_area[-filter_length_oneside-1:] - shapefilter[0:filter_length_oneside+1]
    res = jnp.max(jnp.abs(diff))
    tolerance = jnp.finfo(shapefilter.dtype).eps
    assert res < tolerance
