"""LPF filter test module.
LPF filter is a filter of a line profile generated by LPF Direct method.
This filter is used in MODIT/PreMODIT to convolve the line profile.
"""
import pytest
import jax.numpy as jnp
import numpy as np
from exojax.test.emulate_mdb import mock_wavenumber_grid
from exojax.spec.hitran import normalized_doppler_sigma
from exojax.spec.ditkernel import fold_voigt_kernel_logst
from jax import config

def lpffilter_agreement_with_fold_voigt_kernel_logst():
    config.update("jax_enable_x64", True)
    nu_grid, wav, resolution = mock_wavenumber_grid()
    Ttest = 1200.0
    pmarray = np.ones(len(nu_grid) + 1)
    pmarray[1::2] = pmarray[1::2] * -1.0
    molmass = 28.0101  # mdb.molmass
    nsigmaD = normalized_doppler_sigma(Ttest, molmass, resolution)
    ngammaL_grid = jnp.array([16.23074604, 18.25429762, 20.53013342])
    log_ngammaL_grid = jnp.log(ngammaL_grid)
    Ng_nu = len(nu_grid)

    vk = fold_voigt_kernel_logst(
        jnp.fft.rfftfreq(2 * Ng_nu, 1),
        jnp.log(nsigmaD),
        log_ngammaL_grid,
        Ng_nu,
        pmarray,
    )
    
    tildevk = jnp.fft.irfft(vk[:,0])[:Ng_nu]


    import matplotlib.pyplot as plt
    plt.plot(tildevk, label="tilde vk 0", alpha=0.3)
    plt.yscale("log")
    plt.xscale("log")
    plt.legend()
    plt.savefig("tildevk.png") 

if __name__ == "__main__":
    lpffilter_agreement_with_fold_voigt_kernel_logst()