"""


"""

def count_steps(logfile):
    """count the number of the steps in numpyro/log

    Args:
       log: log or steps.dat generated by (grep steps log > steps.dat)

    Returns:
       True

    
    """
    import numpy as np
    nstep=0
    step=[]
    f=open(logfile,"r")
    w=f.read().split("\n")
    for i in w:
        j=i.split(",")
        if len(j)==3:
            istep=int(j[2].split("steps")[0])
            step.append(istep)
            nstep=nstep+istep
    f.close()
    step=np.array(step,dtype=np.int)
    print("Total steps:",nstep)
    print("# of chain:",len(step))
    print("median of steps in one chain:",np.median(step))
    return True
    
if __name__ == "__main__":
    # usage: python read_step.py log
    import sys
    count_steps(sys.argv[1])
