name: Run pytest
on:
  # Triggers the workflow on push or pull request events but only for the "develop" and "master" branch
  push:
    branches: [ "develop" , "master"]
  pull_request:
    branches: [ "develop" , "master"]


jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # install package	  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python setup.py install

      # install pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # pytest -> JUnit xml
      - name: PyTest
        run: |
          python -m pytest tests/unittests --junit-xml results/pytest.xml
        continue-on-error: true

      # show the results
      - name: Upload Unit Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results (Python 3.8)
          path: results/*.xml

      - name: Download Artifacts
        if: success() || failure()
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml

      - name: Test report
        if: matrix.python == 3.8 && success()
	  env:
    	  CC_TEST_REPORTER_ID: 7d1536340af8c889cc4c43e77005ec3bcf1aab03e53d68b02ddf97bf6f41e57f
	run: |
    	  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    	  chmod +x ./cc-test-reporter
	  ./cc-test-reporter after-build