name: Run pytest
on:
  # Triggers the workflow on push or pull request events but only for the "develop" and "master" branch
  push:
    branches: [ "develop" , "master"]
  pull_request:
    branches: [ "develop" , "master"]


jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v2

      # Pythonの環境をセットアップ
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # pytestをインストール
      - name: Install dependencies
        run: |
	  export PYTHONPATH=./src:$PYTHONPATH
          python -m pip install --upgrade pip
          pip install pytest


      # pytest -> JUnit xml形式で結果を出力
      - name: PyTest
        run: |
          python -m pytest tests/unittests --junit-xml results/pytest.xml
        continue-on-error: true

      # テスト結果の表示
      - name: Upload Unit Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results (Python 3.8)
          path: results/*.xml

      - name: Download Artifacts
        if: success() || failure()
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml

